# Netlify deployment configuration for Philosophical Explorer

[build]
  # Directory to change to before starting build
  base = "/"
  
  # Build command
  command = "npm run build"
  
  # Directory that contains the deploy-ready files
  publish = "build/"

[build.environment]
  # Node version for builds
  NODE_VERSION = "18"
  
  # CI environment variable
  CI = "true"

# Redirect rules for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"