# Cloudflare Pages configuration for Philosophical Explorer
name = "philosophical-explorer"
compatibility_date = "2024-01-01"

[site]
bucket = "./build"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.preview]
vars = { ENVIRONMENT = "preview" }